#! /bin/sh
# /etc/init.d/sgas: start the SGAS accounting server

### BEGIN INIT INFO
# Provides:             sgas
# Required-Start:       $network
# Required-Stop:        $network
# Should-Start:         $time
# Should-Stop:          $time
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    SGAS Accounting server
### END INIT INFO

. /lib/lsb/init-functions

CONFIG_FILE=/etc/sgas.conf

TACFILE=/usr/local/share/sgas/sgas.tac
PIDFILE=/var/run/sgas.pid

DEFAULT_LOGFILE=/var/log/sgas.log
DEFAULT_USER=root

do_start() {
    # get logfile from config file or set to default if not found
    LOGFILE=`grep ^logfile= $CONFIG_FILE | tail -n 1 | cut -f2 -d'='`
    LOGFILE=${LOGFILE:-$DEFAULT_LOGFILE}

    # get runtime user from config file or set to root if not found
    USER=`grep ^user= $CONFIG_FILE | tail -n 1 | cut -f2 -d'='`
    USER=${USER:-$DEFAULT_USER}
    USER_ID=`id -u $USER`
    GROUP_ID=`id -u $USER`

    # start the SGAS LUTS server using twistd
    twistd --pidfile $PIDFILE -l $LOGFILE -y $TACFILE -u $USER_ID -g $GROUP_ID
}

do_stop() {
    kill `cat $PIDFILE` || rm $PIDFILE
}

case "$1" in
  start)
    echo "Starting SGAS accounting server"
    do_start
    ;;
  stop)
    echo "Stopping SGAS accounting server"
    do_stop
    ;;
  restart|reload)
    echo "Restarting sgas accounting server"
    do_stop
    # erhm...
    sleep 1
    do_start
    ;;
  status)
    status_of_proc -p $PIDFILE "twistd" "SGAS Accounting server" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|status}"
    exit 1
    ;;
esac

exit 0
